[package]
name = "class_7"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = { version = "1.5", features = ["derive"] }
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.141"
